### ISSUE TITLE
Opinions about Improvement for Image Viewer

### ISSUE THREAD

**Issue by unique-chan** [Dodant/arma-rs-utils#1]
I really appreciate all your efforts as your code for **Image Viewer** is super-amazing and awesome!!!

However, for a better user experience, I have some improvement opinions as follows:
1. View legend
    - If there are numerous look angles (views), view legend becomes really ugly in Windows!!!
    - Thus, it would be better to **print out the current view (look angle) as a string** somewhere on the image viewer!  
2. Label setting
    - I'm really looking forward to appearing the **ID** feature in the label setting as well!

**Comment by Dodant** [comment]
Angle is indicated on View Box.
ID Label Setting is added.
