### ISSUE TITLE
Please support `meta_*.csv` for better user experience!

### ISSUE THREAD

**Issue by unique-chan** [Dodant/arma-rs-utils#2]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mlv/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mlv/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

i_time | hour | minute | weather | remarks
-- | -- | -- | -- | --
0 | 9 | 0 | sunny | 1
4 | 9 | 0 | sunny |  
5 | 9 | 0 | sunny | 1
6 | 9 | 0 | sunny |  
7 | 9 | 0 | sunny |  
8 | 9 | 0 | sunny |  
9 | 9 | 0 | sunny |  
10 | 9 | 0 | sunny |  

</body>

</html>

It is good if the above attributes are also displayed in the image viewer.
In particular, I'd like to emphasize that your viewer must have to provide the function that sorts images based on the `remarks` attribute. (⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐)

**Comment by Dodant** [comment]
Remart Sort is added.
You're welcome.
